services:
  python:
    image: update-ip-opendns:0.9
    container_name: update-ip-opendns
    volumes:
      - ./app:/app
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # command: ["tail", "-f", "/dev/null"] # Mantener el contenedor en funcionamiento
